<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [
            // Cluster 1: What is the digital euro?
            [1, 'A friend asks you: “In simple terms, what would a digital euro be?”', ['It would be a new private payment app developed by the ECB to compete with banks and card schemes.', 'It would be a digital form of central bank money, for everyday payments and designed to complement banknotes and coins.', 'It would be a crypto-asset issued by the Eurosystem, with a value that could change depending on market demand.', 'It would be a new type of commercial bank deposit, managed directly by the ECB for all euro area residents.'], 2, 'A digital euro would be public money in digital form, issued by the Eurosystem. It would allow people to use central bank money for everyday digital payments, just as they can use banknotes and coins for physical payments.', 200],
            [1, 'A family member says: “If the digital euro is introduced, cash will disappear.” What is the best response?', ['That is correct. The purpose of the digital euro is to replace banknotes and coins with a digital alternative.', 'Incorrect. The digital euro would exist alongside cash, giving people an additional way to pay with central bank money.', 'That depends only on commercial banks, because the Eurosystem does not decide on the future of cash.', 'Cash would remain only for small payments, while the digital euro would become mandatory for most everyday payments.'], 2, 'The digital euro would complement cash, not replace it. Cash would continue to be legal tender and would coexist with the digital euro and private electronic payment methods. The ongoing banknote redesign also underlines the ECB’s commitment to the future of cash.', 150],
            [1, 'Why is the Eurosystem exploring a digital euro when people already have many ways to pay digitally?', ['Because Europe already has a single, fully integrated digital payment solution accepted everywhere in the euro area.', 'Because the main goal is to create an investment product that citizens could hold as an alternative to deposits.', 'Because the aim is to replace existing private payment solutions with one public payment method.', 'Because the digital euro could provide a public, pan-European digital means of payment, available across the euro area and governed in Europe.'], 4, 'The digital euro addresses gaps in today’s payment landscape by offering a digital means of payment that could be used throughout the euro area and is a truly European solution, under European governance. It would give European citizens the choice to make all kinds of payments with our common currency, without being dependent on non-European payment providers.', 200],
            [1, 'Which statement best explains why the digital euro would not be the same as a crypto-asset or stablecoin?', ['The digital euro would be central bank money, issued by the Eurosystem, like banknotes and coins are today.', 'The digital euro would be similar to crypto-assets, but with a lower level of price volatility because it would be used only in the euro area.', 'The digital euro would be privately issued money, supervised by the Eurosystem and backed by euro-denominated assets.', 'The digital euro would be a token used mainly for investment purposes, while stablecoins are used mainly for payments.'], 1, 'The digital euro would be euro in digital form and a direct form of central bank money. Crypto-assets and privately issued digital money, including stablecoins and e-money, have different issuers and legal and operational models. The distinction is not about one being “good” or “bad”, but about who issues the money and what type of claim it represents.', 150],
            // Cluster 2: How would it work?
            [2, 'A friend says: “To use the digital euro, I would need an account directly with the ECB.” What is the best response?', ['Yes, it would work like a personal ECB current account for everyday payments.', 'No, it because the digital euro would only be available to banks and payment service providers, not individuals.', 'Yes, but only if you want to make online payments; offline payments would be managed by commercial banks.', 'No. Users would access digital euro through a payment service provider, such as their bank, either via their existing banking app or through a digital euro app..'], 4, 'Users would not open a personal account directly with the ECB. They would access the digital euro through a supervised payment service provider, such as their bank. Depending on the final distribution arrangements and how their provider offers the service, they could use their banking app or a digital euro app.', 200],
            [2, 'Where could people use the digital euro?', ['Mainly for large-value financial market transactions between banks.', 'In shops, online and to pay another person across the euro area.', 'Only online shopping, because cash already covers in-person payments.', 'Mainly when travelling, to avoid foreign exchange fees outside the euro area.'], 2, 'The digital euro is being designed for everyday payments. People could use it in shops, online or to pay another person, with the aim of offering a payment option that works throughout the euro area.', 150],
            [2, 'What would offline functionality add to the digital euro?', ['Offline payments are not part of the digital euro work, because all digital payments need an internet connection.', 'Offline functionality could allow wallet-to-wallet payments even without an internet connection, bringing digital payments closer to the resilience and immediacy people associate with cash.', 'Offline payments would only be possible for banks, not for individual users.', 'Offline functionality would mainly be used to make payments programmable, so that they can only be spent for specific purposes.'], 2, 'Offline functionality is one of the features that could make the digital euro different from many existing digital payment options. It could allow direct wallet-to-wallet payments without an internet connection, for example in situations where connectivity is unavailable or unreliable.', 200],
            [2, 'Would every merchant have to accept the digital euro?', ['Yes. Every merchant would have to accept it, including businesses that currently accept only cash.', 'No, only merchants already accepting digital payments would be required to accept it.', 'No, acceptance would always be optional.', 'Only large retailers would have to accept it; small merchants would always be exempt.'], 2, 'Merchants that already accept digital payments would be required to accept the digital euro. However, merchants that currently accept only cash would not be required to introduce digital payments solely because of the digital euro.', 150],
            // Cluster 3: Privacy, trust and safeguards
            [3, 'An external peer says: “The ECB would be able to see what I buy with digital euro.” Is that correct?', ['Yes, the ECB and the NCBs would be able to see all individual payments and purchases.', 'Yes, but only for payments above a certain amount. Small payments would remain fully anonymous.', 'No organisation would have any access to payment-related data, even where required by law.', 'No. The Eurosystem could not directly link users to their payments or see what they spent their money on.'], 4, 'Privacy is a core design feature. The digital euro is being designed so that the Eurosystem would not be able to directly identify users from their payment data or see what they bought. For online payments, payment service providers, such as banks, would have access to payment information in a similar way as they do for card payments today. Offline payments would offer cash-like privacy, with payment details known only to the payer and the payee.', 200],
            [3, 'Which statement best explains the difference between online and offline digital euro payments from a privacy perspective?', ['Online and offline payments would provide exactly the same privacy level, because all digital payments need to be processed in the same way.', 'Offline payments would be less private than online payments, because they would require more checks before the payment can be completed.', 'Offline payments could offer cash-like privacy, with payment details known only to the payer and the payee..', 'Offline payments would be fully visible to merchants, banks and the Eurosystem, because they take place without an internet connection.'], 3, 'Offline digital euro payments are being designed to offer cash-like privacy, meaning that payment details would only be known to the payer and the payee. Online payments would also protect privacy from the Eurosystem’s perspective, as the Eurosystem would not be able to directly identify users from their payment data. However, payment service providers, such as banks, would see payment information in a similar way as they do for card payments today.', 200],
            [3, 'If the ECB cannot track individual payments, would digital euro payments be exempt from anti-money laundering and fraud checks?', ['Yes. The main privacy goal is to remove all checks from digital payments.', 'No. The aim is to protect user privacy while still respecting the legal framework, including rules against money laundering and terrorist financing.', 'Yes, but only for online payments. Offline payments would follow stricter legal checks.', 'No. The ECB would review every user’s payment history.'], 2, 'Privacy does not mean that digital euro payments would be outside the law. Anti-money laundering checks aim to prevent money from being used to disguise criminal activity. Fraud checks aim to detect and prevent unauthorised or suspicious payments. For online digital euro payments, payment service providers would apply the checks required by law, while the Eurosystem would not directly track what individual users buy.', 150],
            [3, 'Why are holding limits being considered for the digital euro?', ['To ensure that the digital euro is used mainly for payments, while reducing the risk of large amounts of money moving from commercial bank accounts into digital euro.', 'To discourage frequent use of the digital euro and ensure that people continue to rely mainly on existing private payment methods.', 'To restrict the digital euro to smaller purchases and prevent it from being used for online shopping or other higher-value payments.', 'To make the digital euro a savings product with higher returns than bank deposits.'], 1, 'A holding limit is a cap on the amount of digital euro a person could hold at one time. It would help keep the digital euro focused on payments rather than large-scale saving or investment, while protecting financial stability by reducing the risk of excessive shifts from commercial bank deposits into digital euro.', 200],
            // Cluster 4: Behind the digital euro
            [4, 'What would provide the legal foundation for the digital euro across the euro area?', ['Separate agreements between the ECB and selected banks.', 'A common European legal framework, supported by Eurosystem rules and standards.', 'A voluntary code of conduct developed by payment service providers, with no need for EU legislation.', 'Individual decisions by merchants in each country on whether the digital euro should be treated as public or private money.'], 2, 'A common European legal framework would define key aspects of the digital euro: the Digital Euro Regulation (to be adopted by the co-legislators) would lay down its legal tender status. It would broadly regulate the use of the digital euro, e.g. aspects around access, distribution and acceptance. The Eurosystem would provide rules and technical standards that are in line with the regulatory provisions, to ensure that the digital euro would be a payment solution that works consistently across the euro area.', 200],
            [4, 'Why is a digital euro rulebook needed?', ['To decide separately in each country how the digital euro should work, depending on national payment habits.', 'To replace all existing private payment schemes and prevent banks from developing their own services.', 'To provide common rules, standards and procedures so that digital euro services can be offered consistently by different payment service providers across the euro area.', 'To define the visual design of the digital euro app and marketing campaign.'], 3, 'The rulebook would act as the common scheme framework for the digital euro. It would help ensure that users and merchants have a consistent experience across the euro area, even if services are provided by different intermediaries. In simple terms, it would be the shared set of instructions everyone follows so the digital euro works in the same way everywhere.', 150],
            [4, 'If basic digital euro services are free for individuals, how could the compensation model work?', ['Intermediaries would provide all digital euro services without any compensation, because the digital euro would be a public good.', 'The model aims to balance free basic use for individuals with incentives for intermediaries, reasonable costs for merchants and Eurosystem coverage of its own costs.', 'Individuals would pay monthly subscription fees, while merchants would receive payments for accepting digital euro.', 'Merchants would set the fees paid by consumers, and each country would decide independently how banks are compensated.'], 2, 'The compensation model is designed to balance the interests of different actors. Individuals should be able to use basic digital euro services free of charge, while intermediaries need incentives to distribute and support the service. Merchants should also be protected from excessive costs.', 200],
            [4, 'Which statement best describes the operational system behind the digital euro?', ['The ECB would provide one single app and manage all customer relationships directly.', 'The Eurosystem would provide common infrastructure and rules, while supervised intermediaries would distribute digital euro services and act as the user-facing interface.', 'Each euro area country would develop its own separate digital euro, with different acceptance and settlement rules.', 'The digital euro would rely entirely on existing non-European card scheme infrastructure.'], 2, 'The digital euro would combine a common Eurosystem infrastructure and rules with services provided by supervised intermediaries, such as banks. Payment service providers would manage the customer relationship, including access, wallets and support, while the Eurosystem would provide the public-money and settlement foundation.', 200],
        ];

        foreach ($questions as [$clusterId, $text, $answers, $correct, $explanation, $points]) {
            Question::updateOrCreate(
                ['cluster_id' => $clusterId, 'question' => $text],
                [
                    'answer1' => $answers[0],
                    'answer2' => $answers[1],
                    'answer3' => $answers[2],
                    'answer4' => $answers[3],
                    'answerOK' => $correct,
                    'explanation' => $explanation,
                    'points' => $points,
                ]
            );
        }
    }
}
